global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'authen-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['authen-service:8080']

  - job_name: 'oauth-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['oauth-service:8080']

  - job_name: 'merchant-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['merchant-service:8080']

  - job_name: 'product-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['product-service:8080']

  - job_name: 'supplier-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['supplier-service:8080']
      
  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']